image: atlassian/default-image:3

pipelines:
  branches:
    main:
      - step:
          name: Trigger E2E Tests in pipeline_e2e_tests
          script:
            - echo "Triggering downstream pipeline"
            # Offizieller Atlassian Pipeline
            - pipe: atlassian/trigger-pipeline:5.0.0
              variables:
                BITBUCKET_USERNAME: '@ACCOUNT_EMAIL'              # Username = e-mail
                BITBUCKET_APP_PASSWORD: '$API_TOKEN'              # API-Token: Write Scope
                REPOSITORY: 'waldemarvollmer/pipeline_e2e_tests'
                REF_TYPE: 'branch'
                REF_NAME: 'main'
                CUSTOM_PIPELINE_NAME: 'run-e2e-tests'          # the same name from the second Repo
                # WAIT: 'true'                                 # optional: wait for another Pipe
                DEBUG: 'true'                                  # optional: more Logs

            # Optional: for Logging
            - echo "Trigger-Anfrage abgeschickt – überprüfe in pipeline_e2e_tests → Pipelines"

      # Optional: Second Step, if you want to do something after the trigger
      # - step:
      #     name: More Actions
      #     script:
      #       - echo "Pipeline getriggerd – End"
